build_from:
  armhf: homeassistant/${build_arch}-base-debian:bookworm
  armv7: homeassistant/${build_arch}-base-debian:bookworm
  aarch64: homeassistant/${build_arch}-base-debian:bookworm
  amd64: homeassistant/${build_arch}-base-debian:bookworm
  i386: homeassistant/${build_arch}-base-debian:bookworm
